### ISSUE TITLE
Prevent CanceledError and redundant HTTP calls for identical request data

### ISSUE THREAD

**Issue by stefan-girlich** [simoneb/axios-hooks#1098]
### library versions
the issue appears for these two sets of configurations:

```
# old
"axios": "^0.27.2",
"axios-hooks": "^3.1.3",

# recent
"axios": "^1.1.3",
"axios-hooks": "^4.0.0",
```

### axios-hooks configuration
- `manual: false`, as i require full control of when requests are executed; configured via `makeUseAxios`
- `autoCancel: true`, default value

### code sample
```typescript
const [{ /*...*/ }, refetch] = useAxios<Thing[]>({
        url: `/things?id=${someId}`,
        method: 'GET',
})

useEffect(() => {
    if (!someId) return
    refetch()
}, [someId, refetch])
```

### behaviour
- the `useEffect()` callback function is called multiple times, invoking `refetch()` multiple times
- for each call, identical method, URL and headers are used
- the first call is canceled, resulting in an unhandled runtime error: `CancelToken.js?f5d8:60 Uncaught (in promise) CanceledError {message: 'canceled', name: 'CanceledError', code: 'ERR_CANCELED',`
- this error is not exposed as a result of the hook, so there is no way I can at least silence it
- i can use `autoCancel: false` to get rid of the error, but not of the duplicate invokation

## goal
subsequent invokations of `refetch` are ignored when pending invokation has exact same method, URL and headers.
is there any way to do so without manualy bookkeeping of the last used exact same request data? thanks so much!

**Comment by jeffcjohnson** [comment]
I think you may have meant to set {manual: true} so that it only executes when you call refetch.  In my experience, refetch will bypass cache and execute even if all params are the same as the last execute.

There's another neat pattern where you can have it only execute if someId is valid without useEffect:

```
const [{ /*...*/ }, refetch] = useAxios<Thing[]>(`/things?id=${someId}`, {manual: !someId})
```

The code above will set manual true when someId is falsy and therefore not call the API.  When someId changes, it will automatically call the API only once.   You can also then later call refetch as the result of something like a user clicking a refresh button.

GET is the default method and the first param can be a config or string (url) so it just passes the URL as the first param instead of a config.

I don't see this in the documentation but I definitely saw this somewhere as it blew my mind when I saw it.
