### ISSUE TITLE
Cache is not working

### ISSUE THREAD

**Issue by pablonunezg** [simoneb/axios-hooks#118]
I tried to use the cache and this is not working for me.

I attached the index.js and App.js and the versions from packages that I am using.

I put this in index.js

const axios = Axios.create({
    baseURL: 'https://api.myjson.com/',
})

const cache = new LRU({ max: 10 })

configure({ cache, axios })

and the following in App.js

import React, { useState } from 'react';
import './App.css';

import useAxios from 'axios-hooks'

function App() {

  const [name, setName] = useState("pablo");

  const [{ data, loading, error }, refetch] = useAxios('bins/820fc', { manual: false, useCache:true });

  const handleSubmit = event => {
    event.preventDefault();
    refetch();
  }

  if (loading) return <div className="App-header">Loading...</div>

  if (error) return <div className="App-header">Error!</div>

  return (
    <div className="App">
      <header className="App-header">
        <form onSubmit={handleSubmit}>
          <label htmlFor="name">Enter your name: </label>
          <input
            id="name"
            type="text"
            value={name}
            onChange={e => setName(e.target.value)}
          />
          <button type="submit">Submitss</button>
        </form>
        <div>{JSON.stringify(data, null, 2)}</div>
      </header>
    </div>
  );
}

export default App;

and I am using the following versions:

    "axios": "^0.19.0",
    "axios-hooks": "^1.9.0",
    "lru-cache": "^5.1.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",

![useAxiosCache](https://user-images.githubusercontent.com/3289826/70994829-a5f88e00-2094-11ea-9f0a-31ecf1a9ab17.png)

Thanks for you great work!!

**Comment by simoneb** [comment]
It would be good if you could create a repro on CodeSanbox for instance. In any case, from a quick looks it seems that you're expecting that refetching uses the cache, which is doesn't by default.

See the [docs](https://github.com/simoneb/axios-hooks#useaxiosurlconfig-options) and notice the difference between the `useCache` option, which can occur in 2 places:

- when invoking the hook (it's true by default)
- when invoking the execute (refetch) function (it's false by default, because we assume that if you're refetching you probably want to skip the cache)

Does that clarify?

**Comment by pablonunezg** [comment]
many thanks for your help!!  this is working now :)
