### ISSUE TITLE
Update the cache for an endpoint using a manual execute on another screen

### ISSUE THREAD

**Issue by SMJ93** [simoneb/axios-hooks#240]
Hey,

Is it possible to update the cache using a manual execute on another screen?

For example:

```
// Home screen
const [{data, loading}, getEndpoint] = useAxios(
    {
      url: '/endpoint',
      method: 'get',
    },
    {useCache: true},
  );

// I want data here to use the cached value e.g. [1,2]
```

```
// Second screen
const [{loading: loadingPayees}, getEndpoint] = useAxios(
    {
      url: '/endpoint',
      method: 'get',
    },
    {manual: true},
  );

const onPressDeletePayee = async () => {
    // Hit another endpoint that deletes some data so it would now be [1]
    if (response?.success) {
      await getEndpoint(); // I want this to update the cache on the home screen here
      navigation.navigate(AuthorisedRoutes.HOME); // Navigate to home screen
    }
  };
```

```
// Home
I would expect the data on the home screen to show [1], but it still shows [1,2]
```

**Comment by simoneb** [comment]
Can you define what you mean by "screen"?

**Comment by SMJ93** [comment]
Sorry, In React Native you can have multiple screens - we are using react navigation v5.

I am hitting the same endpoint on 2 different screens (both using the cache). They both initially return [1].

If hit refresh on one screen it could return new data e.g. [1,2].

I would expect it to update the cache and see [1,2] on both screens. 

But I don't, the screen where I hit refresh shows [1,2], but on the other screen I still see [1].

**Comment by simoneb** [comment]
Can you post sample code to show the issue? You can use this example as a starter: https://snack.expo.io/@simoneb/axios-hooks-react-native

**Comment by simoneb** [comment]
If that's helpful, I created an example with react router: https://github.com/simoneb/axios-hooks/blob/master/README.md#examples

**Comment by SMJ93** [comment]
Hi @simoneb, sorry for the delay.

Here is a simple example:

Page 1:
```

**Comment by simoneb** [comment]
@SMJ93 can you share the codesandbox please?

**Comment by simoneb** [comment]
Ok I see the issue. When using `refetch`, the current default behavior is that the cache is skipped. The problem is that the cache not only is skipped when loading the data (thereby hitting the real endpoint)  but it's also skipped when the response is returned, therefore it doesn't overwrite what's currently in the cache.

I think that skipping the cache should only skip it for the request, but then it should put the response in the cache so the latest response is reflected everywhere

**Comment by SMJ93** [comment]
yep! agreed. We've decided to use Redux Toolkit for now due to deadlines etc so no rush for this!

**Comment by simoneb** [comment]
@SMJ93 I started working on this request, which requires considerable changes to the caching mechanism. I published a pre release version of the package and used it in [this example](https://codesandbox.io/s/axios-hooks-caching-nm62v) that I set up starting from yours, to show how caching behaves in different situations. I would appreciate if you could take a look.

**Comment by SMJ93** [comment]
@simoneb looks great! Thanks for adding this so quickly 👍

**Comment by simoneb** [comment]
@SMJ93 I'm planning to release this change with a major 2.0.0 release (because it's not a backwards compatible change). Meanwhile there have been a couple of intermediate releases. Can you please check that the latest prerelease 2.0.0-1 works for you? I also updated the example to use it to make sure that I didn't break anything.

This new caching behavior makes sense to me but it introduces possibly breaking changes, including one I've already encountered. Because manual refetches now hit the cache, invoking the refetch function in event handlers now causes issues:

```jsx
<button onClick={refetch} />
```

That's because the signature of the refetch function is `(config, options) => Promise`.

In the previous implementation, providing a "config" which was actually a DOM (or better, React Synthetic Event) wasn't a big deal but with the new behavior, the config is used to create the cache key, thereby causing errors when it's an event.

Exceptionally, considering that invoking refetch in a click handler is a somewhat common scenario, I'm thinking to intercept and identify that the argument provided to the refetch function is an event and ignore it in that case, to avoid requiring too many changes to existing codebases, but this is going to be a breaking change anyway.

I'd like to hear your thoughts on this.

**Comment by SMJ93** [comment]
Hi @simoneb, `2.0.0-1` looks good to me!

I think your proposed solution sounds good. Might be worth adding your explanation above to the refetch documentation or codebase just so people understand why you've done it this way.

Good work @simoneb  👍
