### ISSUE TITLE
Question regarding the request function

### ISSUE THREAD

**Issue by philwindsor** [simoneb/axios-hooks#254]
I'm using the hook in auto mode (manual: false) and using the error returned by the hook. The request function which is the core of the hook throws an error after dispatching it. I can see why this is done for manual requests but for auto handling (manual: false), is it possible to not throw the error?

code:

````async function request(config, dispatch) {
    try {
      dispatch({ type: actions.REQUEST_START })
      const response = await axiosInstance(config)
      dispatch({ type: actions.REQUEST_END, payload: response })
      return response
    } catch (err) {
      if (StaticAxios.isCancel(err)) {
        return
      }

      dispatch({ type: actions.REQUEST_END, payload: err, error: true })
      throw err
    }
  }
````

example:

````async function request(config, dispatch) {
    try {
      dispatch({ type: actions.REQUEST_START })
      const response = await axiosInstance(config)
      dispatch({ type: actions.REQUEST_END, payload: response })
      return response
    } catch (err) {
      if (StaticAxios.isCancel(err)) {
        return
      }

      dispatch({ type: actions.REQUEST_END, payload: err, error: true })
      if(options.manual){
         throw err
      }
    }
  }
````

Or expose another option that defaults to throwing the error but can be set by calling code

````async function request(config, dispatch) {
    try {
      dispatch({ type: actions.REQUEST_START })
      const response = await axiosInstance(config)
      dispatch({ type: actions.REQUEST_END, payload: response })
      return response
    } catch (err) {
      if (StaticAxios.isCancel(err)) {
        return
      }

      dispatch({ type: actions.REQUEST_END, payload: err, error: true })
      if(options.throwError){
         throw err
      }
    }
  }
````
The above examples would mean options needs passing to a few extra functions but should be easy enough?

This was highlighted within another issue a while back #187 as it clutters up test out.

**Comment by simoneb** [comment]
Can you please explain the reason why you don't want the exception to be thrown? Meanwhile, I posted an [example](https://codesandbox.io/s/axios-hooks-error-handling-gvi41) about how to do error handling, the rationale being:

- when the request is performed by the hook itself, the error is caught and it's available in the error property returned by the hook
- when the request is performed manually, the error is thrown by the "refetch" function, because if you're invoking it manually, the assumption is that you want to handle the response yourself, including a possible exception. both the data and the error will still be available in the hook result, but the error you'll have to handle yourself

**Comment by simoneb** [comment]
Stale, closing.
