### ISSUE TITLE
How to deal with non success responses

### ISSUE THREAD

**Issue by krolow** [simoneb/axios-hooks#348]
E.g get a 400 from the request 

It looks like it throw the error https://github.com/simoneb/axios-hooks/blob/master/src/index.js#L177

**Comment by simoneb** [comment]
A non-200 response status code will generate an error. Depending on how you're doing the request (either using the auto or manual request) you will get it in the `error` property of the return value of the hook or a rejected promise, respectively.

There's an example about error handling in the [docs](https://github.com/simoneb/axios-hooks#examples).

**Comment by imekachi** [comment]
I have an issue when receiving a non-200 response while on server side rendering.

Instead of the hook catches all errors from fetching and put it in `error` object, it let the errors from executing axios pass through and break the node process(node v15) because of unhandled promise rejection.

As you can see in the terminal (I think you have to fork it to see it)
https://codesandbox.io/s/axios-hooks-ssr-error-tpxjk?file=/pages/index.js

**Comment by simoneb** [comment]
> I have an issue when receiving a non-200 response while on server side rendering.
> 
> Instead of the hook catches all errors from fetching and put it in `error` object, it let the errors from executing axios pass through and break the node process(node v15) because of unhandled promise rejection.
> 
> As you can see in the terminal (I think you have to fork it to see it)
> https://codesandbox.io/s/axios-hooks-ssr-error-tpxjk?file=/pages/index.js

Other people have reported issues of various types around SSR, but nobody sent a PR to fix them. This issue may fall into that category and a PR would be greatly appreciated.
