### ISSUE TITLE
can not read property 'data' of undefined, any idea? thank you.

### ISSUE THREAD

**Issue by singleseeker** [simoneb/axios-hooks#357]
![image](https://user-images.githubusercontent.com/520698/97374981-996bd580-18f4-11eb-9505-5601482a3150.png)

**Comment by simoneb** [comment]
Can you provide a repro?

**Comment by svenadlung** [comment]
Same happens to us. We are actually sending some requests with at least 1 second of delay and the server doesn't answer quickly. We can reproduce easily by slowing down with throttling in network tab (Slow 3G). Results in cancelled requests and the error message shown above.

**Comment by simoneb** [comment]
I am not sure what is happening, I tried to put together [an example here](https://codesandbox.io/s/axios-hooks-357-repro-m3sgx?file=/src/index.js) which simulates a slow server response with the ability to trigger multiple requests, but I haven't been able to reproduce the issue. Can you please take a look and try to reproduce it, or provide an alternative repro?

**Comment by svenadlung** [comment]
@simoneb you are right. We tried to reproduce in a sandbox as well, but it looks just fine. We are using `configure()` as well with caching, but this didn't causes the error neither. In our case it happens only sometimes. We are not quite sure what it is related to but it's only with many requests and delayed responses. How is it for @singleseeker ? Can you have a look at the sandbox?

**Comment by simoneb** [comment]
@svenadlung after looking more closely into the code, and assuming that you are using the latest version of this library, I concluded that only way to cause this issue is a custom configuration of axios that you must be providing and which is causing some invariants to not be respected. For instance, if you are using interceptors and not returning a response in some cases, this is what will happen and I have reproduced it in [the repro](https://codesandbox.io/s/axios-hooks-357-repro-m3sgx?file=/src/index.js) by providing such an interceptor.

I'm going to close this issue as the issue lies in user land.

**Comment by svenadlung** [comment]
@simoneb Oh man, so good 👍 You are right. 

Our custom error handling (in axios interceptors) handles errors with a response but in this case there is no `error.response` and we do not return anything. But as you said it expects a return. Now we `return Promise.reject(error)` and everything works like a charm. Old requests get cancelled and new ones are running perfectly without any react error.

Thanks a lot!
