### ISSUE TITLE
Reset (back to initial state)

### ISSUE THREAD

**Issue by dkershner6** [simoneb/axios-hooks#359]
I have had a couple use cases for this, situations where I am using context to share the results, and the page inside the context changes an ID, and I need to make new calls.

In current form, I have to wrap data, loading, and error with a more complex status and data object that pays attention to another state variable, tracking if the reset has occurred.  

This would be simpler inside `useAxios`, by just creating one more action that dispatches back to the original defaults, and we could reset the cache too, optionally

**Comment by simoneb** [comment]
Can you give a more concrete example? If you use a codesandbox to show what this library does and what you would like to obtain instead, it would be easier to understand.

**Comment by dkershner6** [comment]
Not sure if a sandbox makes sense, would be pseudo-code, so ill just try and explain more explicitly here.

`const [{data,}, getData] = useAxios('', {manual: true});`

This is present, and lets pretend that when we call `getData(17)`, data turns from `undefined` to `{ testData: 17 }`.

What I would like, is a way to get `data` back to `undefined`, i.e.

`const [{data,}, getData, resetData] = useAxios('', {manual: true});`

`resetData()`

So I can have a clean slate, and then call `getData(18)`.

Hopefully that helps.

**Comment by dkershner6** [comment]
The reason behind this is when useAxios is somewhere reusable (i.e. React.Context) and the query changes based on user input.  In these cases it can be really helpful to be able to re-enter your initial state, so that everything can be choreographed one way and then that way can be reused (rather than creating an initial flow and a refresh flow).

**Comment by simoneb** [comment]
Thanks for explaining @dkershner6. It doesn't really feel like this is something that fits into this library to be honest. This feels like a use case that should be achieved in user code, because it's specific to your application.

In other words, I wouldn't want to include in this library anything that's not generic enough to deserve living therein, and anything extra should be implemented in user code, especially if it's something easy to do. 

For instance, even though you didn't provide a concrete example, I believe your use case can be easily accomplished by keeping some additional state around, and considering how easy it is to compose React hooks (e.g. wrap useAxios into a custom hook which adds that specific behavior based on React context), I don't see a compelling reason to include this behavior in the library.

**Comment by dkershner6** [comment]
Works for me, just needed a clear direction, thanks!

**Comment by atinder** [comment]
Today, I came across the same use case where I needed to reset the data for a manual request.
I agree we can have additional useState in our app to handle this.

Although from the perspective of an end-user of the library, `reset` seems quite a handy helper, just like the `refetch`  function.

**Comment by simoneb** [comment]
@atinder would you like to send a pull request? it should be fairly simple to implement

**Comment by atinder** [comment]
sure @simoneb I'll peek into the source code this week.

**Comment by damianobarbati** [comment]
is this currently implemented?

**Comment by damianobarbati** [comment]
@atinder keep in mind, with that signature, everybody using eslint and not using the `cancel` method will be forced to add `eslint-disable-line` to not have the `unused-vars` error.

**Comment by simoneb** [comment]
If somebody would like to send a pull request please do so!
