### ISSUE TITLE
"Can't perform a React state update on an unmounted component." after use axios.interceptors.response!

### ISSUE THREAD

**Issue by singleseeker** [simoneb/axios-hooks#371]
You could get the execute code by the following URL.

https://codesandbox.io/s/axios-hooks-configuration-example-forked-yut2g?file=/src/index.js:346-373

After the page load, click the link "FetchData", before it finished, quickly click "Home".

You`ll see the error on the console.
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in FetchData (at src/index.js:49)
```
![2020-12-29 22 07 22](https://user-images.githubusercontent.com/520698/103289595-8b385380-4a22-11eb-8161-c7f99aff9318.gif)

**Comment by simoneb** [comment]
The problem is in the response interceptor. We are [detecting if the error is caused by a cancellation](https://github.com/simoneb/axios-hooks/blob/master/src/index.js#L173) due to the component unmounting and avoiding the state update in that case.

See the [updated example](https://codesandbox.io/s/axios-hooks-configuration-example-forked-piup6?file=/src/index.js).

If you need to customize the response interceptor you'll need to preserve this invariant or we won't know that we should avoid the state update.

**Comment by singleseeker** [comment]
wow, @simoneb , big thanks.

It works now.

**Comment by simoneb** [comment]
You're welcome
