### ISSUE TITLE
Performance with Large Requests

### ISSUE THREAD

**Issue by kentongray** [simoneb/axios-hooks#381]
Hello again, we've been using axios-hooks for a bit and absolutely love it. However we are currently running into a bit of a performance issue where we have very large requests (the axios data prop) and (we think) because of the JSON.serialize on the memo dependency we are hitting some performance bottlenecks because of the constant serialization.

Any of these options would be fine with me:
1) A flag to use reference comparison
2) Ability to specify your own comparator function
3) Checking if Object is frozen and if so use a reference check

Happy to implement the change but was curious if there was any of those options you prefer over the other (or if there is some other way I'm not thinking of)

**Comment by simoneb** [comment]
Good catch. I think that the config serialization may not be necessary in fact, see https://github.com/simoneb/axios-hooks/pull/382. This would introduce a breaking change because if you were providing an object and mutating it, it would re-execute the request (because the serialized representation would change) whereas with this change it would not. But since all tests pass I guess we never really relied on this behavior and we can introduce the breaking change, while getting rid of a potentially serious performance issue.

**Comment by simoneb** [comment]
I had to revert the change done in 2.4.0, it was an oversight. Without that trick of serializing the configuration each time you'd render a component with a non primitive config (e.g. `{ url: 'whatever' }`) the hook would also rerender because it would detect a new configuration.

Release 2.4.1 fixes the regression, I'll release a new version with a different way of obtaining this optimization.

**Comment by kentongray** [comment]
No prob! I actually tried it out and had the same experience was going to investigate and see if there was anything I was doing obviously wrong. Thanks again for your hard work on this very handy project

**Comment by simoneb** [comment]
I have released prerelease version 2.5.0-0 which does deep object comparison instead of serialization. Can you try it out and let me know if it addresses the performance issue without introducing any issues?

**Comment by kentongray** [comment]
@simoneb just tested on our app and so far seems flawless and the performance issue is resolved. I'll let you know if I see anything else but I think so far so good!

**Comment by simoneb** [comment]
Let's let it settle for a little while before cutting a new release. If you could use this in your setup and let me know if you find any issues it would be great.

**Comment by simoneb** [comment]
If no issue found I'll release this later today

**Comment by kentongray** [comment]
been running like a champ on our prod release, no issues found

**Comment by simoneb** [comment]
Thanks for checking. I released a final version 2.5.0
