### ISSUE TITLE
Failing manual fetch after successful fetch doesn't clear data 

### ISSUE THREAD

**Issue by rsdrsd** [simoneb/axios-hooks#387]
When I've done a successful manual fetch and after that I execute it again and if it than fails, the data is still filled with the data of the previous request. I would expect it to be undefined. The reverse works as expected. If I have a failed fetch and after that I do another fetch which succeeds the error is set to null.

Is this a bug or expected behavior?

**Comment by simoneb** [comment]
This is expected and by design. There are reasons in favor of both options, none is necessarily more correct than the other. The reason why the error is reset (your second case above) is because you do want to know when a successful fetch happens, and you wouldn't know it if the error isn't reset. On the other hand, when a fetch fails but you have previously loaded data, you will still have that data because you may want to keep showing it to the user, but you will also have the error so you can tell the user there was an error.
