### ISSUE TITLE
Not setting returned data when the http Status is not 'OK'

### ISSUE THREAD

**Issue by onnobaudouin** [simoneb/axios-hooks#398]
When:

```javascript
 const [
    {
      data
      loading,
      error,
    },
  ] = useAxios(DATA_URL);
```
When the result is , e.g. HTTP STATUS 400+ `data` is not updated to the content of the return even if it contains valid JSON / other. (it remains at undefined).  It *seems* to check the HTTP Status code , then throws before handling the content?

HTTP has no issues with erroneous status codes return data. 

Also:

-  if the first call completes successfully (200) then `data` is set correctly
- When the next call is 400 then `data` does not change - i.e. it should either reset `data` or used the body of the error. In this case i need to manually check for 'error'

**Comment by simoneb** [comment]
What you describe is not necessarily right nor necessarily wrong, just an implementation decision. When the status code is not considered successful, the response is stored in the error property of the first item of the array returned by the invocation of the hook. The reason why the data stays there when an error occurs is because you may want to keep showing the previous successful response. Again, the behavior implemented in the hook is not absolutely right, it's just an implementation decision. 

I would be happy to make it more flexible, but I'm not sure how to let the user tune this behavior.

**Comment by onnobaudouin** [comment]
@simoneb : thank you - i did not know the error is very much the 'axios' error. Personally i think 'data' should always return the 'data' of the call - it is not really ambiguous. I.e. my 'error' data should overwrite the previous data as that was result of that call. i.e. useAxios should not , imho make decisions about how the data is to be used, only represent the state of the XHR call? You *could* create an extra valuable called 'lastCorrectData' or something for those who need that to be clear. But i totally understand that implementation decisions have been made, just my feeling they are too 'smart' and 'hide' things...  Otherwise excellent work and for now i work around it - more a headsup on where, one developer, did not understand the full contract of the hook.

**Comment by simoneb** [comment]
The API is really simple actually and is in a sense consistent with axios. If the status code represents an error axios returns a rejected promise, and axios-hooks stores that in the error property. You could argue that axios' behavior of rejecting the returned promise in case the status code represents a failure is an implementation choice too, one which the native fetch doesn't do for example.
I'll close this issue but if you have ideas how to improve without breaking the API feel free to reopen it.
