### ISSUE TITLE
Suggested approach for PUT/PATCH/POST

### ISSUE THREAD

**Issue by stevewillard** [simoneb/axios-hooks#6]
This package is great - thank you!

Do you have a suggested approach for mutations? Maybe something like `usePost` or `usePut`, which might return a function/promise.

**Comment by simoneb** [comment]
Thanks! Haven't thought much about this, but I think an API I would like, rather than introducing new root level exports, is something like this:

```
const [{ data, loading, error }, triggerRequest] = useAxios(
    'https://jsonplaceholder.typicode.com/todos/1',
    { skip: true }
  )

....

triggerRequest({ arguments to be merged with the original request configuration })
```

So the existing API would be unchanged, but we could pass options as a second argument, for instance with a `skip` (or maybe `manual`) properties to indicate that the request is not triggered right away but only when the second item of the array of the return value is invoked.

What do you think?

**Comment by stevewillard** [comment]
I definitely like the merging of options - I was thinking the same thing!

Not loving the `{ skip }` option, manual is a bit better, but I like the general idea of what you're saying.

**Comment by simoneb** [comment]
Version 1.1.0 addresses this now. More details in the updated docs.

**Comment by stevewillard** [comment]
Thank you! It looks great.
