### ISSUE TITLE
Render Error exception

### ISSUE THREAD

**Issue by moas** [simoneb/axios-hooks#775]
Hi

I implement a refresh token via axios interceptor like:

```
axios.interceptors.response.use(
        (response) => response,
        async (error) => {
            const config = error.config;
            const authError = (error?.response?.status === 403 || error?.response?.status === 401)

            if(authError) {
                if(!config._retry) {
                    config._retry = true;
                    await fetchToken()
                    return axios.request(config);
                } else {
                    setAuthRequired(true)
                    return Promise.resolve()
                }
            }
            return Promise.reject(error);
        }
 );

```

But I receive an exception

```
TypeError: undefined is not an object (evaluating 'action.payload.data')

This error is located at:
    in LoadingScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
```

I was hoping to trigger a modal above the current page. Can you help me understand my mistake and fix it ?! thx

**Comment by vladi-strilets** [comment]
This error is from your component code, it is not related to the `axios-hooks` or `axios.interceptors`.

**Comment by simoneb** [comment]
The problem you're seeing is because you're not respecting axios interceptor's invariants. From a response interceptor you should return a promise which is a proper axios response, or an error. I appreciate this is not clearly stated in the axios docs and by reading your code I cannot see exactly which line of code is causing the issue, but I believe that returning a plain `Promise.resolve` is one such possible issue.

**Comment by simoneb** [comment]
@moas I'm going to close this issue, in the docs there is a working example of token refresh which should put you on the right path.
